//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimeAX.fonts.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimeStatusFromUser
    {
        public int Id { get; set; }
        public int AnimeId { get; set; }
        public int UserId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Anime Anime { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
