//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimeAX.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anime()
        {
            this.AnimeGenre_Anime = new HashSet<AnimeGenre_Anime>();
            this.AnimeStatusFromUser = new HashSet<AnimeStatusFromUser>();
            this.FavoritesAnime = new HashSet<FavoritesAnime>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContentText { get; set; }
        public byte[] FileBit { get; set; }
        public int AnimeTypeId { get; set; }
        public int AnimeStatusId { get; set; }
        public int AgeLimitId { get; set; }
        public byte[] Image { get; set; }
    
        public virtual AgeLimit AgeLimit { get; set; }
        public virtual AnimeStatus AnimeStatus { get; set; }
        public virtual AnimeType AnimeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimeGenre_Anime> AnimeGenre_Anime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimeStatusFromUser> AnimeStatusFromUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoritesAnime> FavoritesAnime { get; set; }
    }
}
