//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimeAX.fonts.Models.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnimebdEntities1 : DbContext
    {
        public AnimebdEntities1()
            : base("name=AnimebdEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<AgeLimit> AgeLimit { get; set; }
        public virtual DbSet<Anime> Anime { get; set; }
        public virtual DbSet<AnimeGenre> AnimeGenre { get; set; }
        public virtual DbSet<AnimeGenre_Anime> AnimeGenre_Anime { get; set; }
        public virtual DbSet<AnimeStatus> AnimeStatus { get; set; }
        public virtual DbSet<AnimeStatusFromUser> AnimeStatusFromUser { get; set; }
        public virtual DbSet<AnimeType> AnimeType { get; set; }
        public virtual DbSet<FavoritesAnime> FavoritesAnime { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
